In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression


In [2]:
df = pd.read_excel('data-numeric.xlsx')

In [3]:
df.head()

ID  make  months_old  power  sale_type  num_owners  gear_type  \
0  97860    26         240    210          2           3          2   
1  27821    11          54    487          5           1          2   
2  98251    26          14    368          5           1          2   
3  98222    26          17    368          5           1          2   
4  62294     3           8    388          3           1          1   

   fuel_type     kms   price  
0          5  202000  999999  
1          5   30000  685000  
2          5    2800  470000  
3          5     145  445000  
4          5    2500  263724

In [4]:
df.index

RangeIndex(start=0, stop=21418, step=1)

In [5]:
df.index = range(1,21419)

In [6]:
df.index

RangeIndex(start=1, stop=21419, step=1)

In [8]:
## x data
x= np.array([df['make'] , df['months_old'] , df['power'], ]) 
print (x)

[[ 26  11  26 ...  24  29  29]
 [240  54  14 ... 261 316 316]
 [210 487 368 ...  73  46  46]]


In [11]:
x= x.T
print (x)

[[ 26 240 210]
 [ 11  54 487]
 [ 26  14 368]
 ...
 [ 24 261  73]
 [ 29 316  46]
 [ 29 316  46]]


In [12]:
x.shape

(21418, 3)

In [14]:
## test
x[0]

array([ 26, 240, 210])