In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [255]:
b= [1,1,1]
LR = 0.0001 ## learning rate
x1=0 ## x1 variable
x2=0 ## x2 variable
y_hat=0 ## y hat 

def regr(x1, x2):
    y_hat= b[0]+b[1]*x1+b[2]*x2
    return y_hat

print (regr(1,1))
 

3


In [147]:
col_names = ["1) Alcohol", "2) Malic acid" ,"3) Ash" ,"4) Alcalinity of ash",  "5) Magnesium" ,"6) Total phenols" 
             ,"7) Flavanoids" ,"8) Nonflavanoid phenols", "9) Proanthocyanins" ,"10) Color intensity", "11) Hue" ,
             "12) OD280/OD315 of diluted wines" ,"13) Proline" ]
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
                names = col_names, 
                header = None)
df.index = range(1,179)
df.head()

1) Alcohol  2) Malic acid  3) Ash  4) Alcalinity of ash  5) Magnesium  \
1       14.23           1.71    2.43                  15.6           127   
2       13.20           1.78    2.14                  11.2           100   
3       13.16           2.36    2.67                  18.6           101   
4       14.37           1.95    2.50                  16.8           113   
5       13.24           2.59    2.87                  21.0           118   

   6) Total phenols  7) Flavanoids  8) Nonflavanoid phenols  \
1              2.80           3.06                     0.28   
2              2.65           2.76                     0.26   
3              2.80           3.24                     0.30   
4              3.85           3.49                     0.24   
5              2.80           2.69                     0.39   

   9) Proanthocyanins  10) Color intensity  11) Hue  \
1                2.29                 5.64     1.04   
2                1.28                 4.38     1.05   
3                2.81                 5.68     1.03   
4                2.18                 7.80     0.86   
5                1.82                 4.32     1.04   

   12) OD280/OD315 of diluted wines  13) Proline  
1                              3.92         1065  
2                              3.40         1050  
3                              3.17         1185  
4                              3.45         1480  
5                              2.93          735

In [134]:
## y data
y_train = np.array(df['12) OD280/OD315 of diluted wines'])
y_train = y.reshape(len(y),1)
print (y_train)

[[3.92]
 [3.4 ]
 [3.17]
 [3.45]
 [2.93]
 [2.85]
 [3.58]
 [3.58]
 [2.85]
 [3.55]
 [3.17]
 [2.82]
 [2.9 ]
 [2.73]
 [3.  ]
 [2.88]
 [2.65]
 [2.57]
 [2.82]
 [3.36]
 [3.71]
 [3.52]
 [4.  ]
 [3.63]
 [3.82]
 [3.2 ]
 [3.22]
 [2.77]
 [3.4 ]
 [3.59]
 [2.71]
 [2.88]
 [2.87]
 [3.  ]
 [2.87]
 [3.47]
 [2.78]
 [2.51]
 [2.69]
 [3.53]
 [3.38]
 [3.  ]
 [3.56]
 [3.  ]
 [3.35]
 [3.33]
 [3.44]
 [3.33]
 [2.75]
 [3.1 ]
 [2.91]
 [3.37]
 [3.26]
 [2.93]
 [3.2 ]
 [3.03]
 [3.31]
 [2.84]
 [2.87]
 [1.82]
 [1.67]
 [1.59]
 [2.46]
 [2.87]
 [2.23]
 [2.3 ]
 [3.18]
 [3.48]
 [1.93]
 [3.07]
 [1.82]
 [3.16]
 [2.78]
 [3.5 ]
 [3.13]
 [2.14]
 [2.48]
 [2.52]
 [2.31]
 [3.13]
 [3.12]
 [3.14]
 [2.72]
 [2.01]
 [3.08]
 [3.16]
 [2.26]
 [3.21]
 [2.75]
 [3.21]
 [2.27]
 [2.65]
 [2.06]
 [3.3 ]
 [2.96]
 [2.63]
 [2.26]
 [2.74]
 [2.77]
 [2.83]
 [2.96]
 [2.77]
 [3.38]
 [2.44]
 [3.57]
 [3.3 ]
 [3.17]
 [2.42]
 [3.02]
 [3.26]
 [2.81]
 [2.78]
 [2.5 ]
 [2.31]
 [3.19]
 [2.87]
 [3.33]
 [2.96]
 [2.12]
 [3.05]
 [3.39]
 [3.69]
 [3.12]
 [3.1 ]
 [3.64]


In [175]:
## x data
x1_train= np.array(df['6) Total phenols'])
x1_train= x1_train.reshape(len(x1_train),1)
x2_train= np.array(df['7) Flavanoids'])
x2_train= x2_train.reshape(len(x2_train),1)
print (x1_train)

[[2.8 ]
 [2.65]
 [2.8 ]
 [3.85]
 [2.8 ]
 [3.27]
 [2.5 ]
 [2.6 ]
 [2.8 ]
 [2.98]
 [2.95]
 [2.2 ]
 [2.6 ]
 [3.1 ]
 [3.3 ]
 [2.85]
 [2.8 ]
 [2.95]
 [3.3 ]
 [2.7 ]
 [3.  ]
 [2.41]
 [2.61]
 [2.48]
 [2.53]
 [2.63]
 [2.85]
 [2.4 ]
 [2.95]
 [2.65]
 [3.  ]
 [2.86]
 [2.42]
 [2.95]
 [2.35]
 [2.7 ]
 [2.6 ]
 [2.45]
 [2.4 ]
 [3.  ]
 [3.15]
 [2.45]
 [3.25]
 [2.64]
 [3.  ]
 [2.85]
 [3.25]
 [3.1 ]
 [2.75]
 [2.88]
 [2.72]
 [2.45]
 [3.88]
 [3.  ]
 [2.6 ]
 [2.96]
 [3.2 ]
 [3.  ]
 [3.4 ]
 [1.98]
 [2.05]
 [2.02]
 [2.1 ]
 [3.5 ]
 [1.89]
 [2.42]
 [2.98]
 [2.11]
 [2.53]
 [1.85]
 [1.1 ]
 [2.95]
 [1.88]
 [3.3 ]
 [3.38]
 [1.61]
 [1.95]
 [1.72]
 [1.9 ]
 [2.83]
 [2.42]
 [2.2 ]
 [2.  ]
 [1.65]
 [2.2 ]
 [2.2 ]
 [1.78]
 [1.92]
 [1.95]
 [2.2 ]
 [1.6 ]
 [1.45]
 [1.38]
 [2.45]
 [3.02]
 [2.5 ]
 [1.6 ]
 [2.55]
 [3.52]
 [2.85]
 [2.23]
 [1.45]
 [2.56]
 [2.5 ]
 [2.2 ]
 [1.68]
 [1.65]
 [1.38]
 [2.36]
 [2.74]
 [3.18]
 [2.55]
 [1.75]
 [2.48]
 [2.56]
 [2.46]
 [1.98]
 [2.  ]
 [1.63]
 [2.  ]
 [2.9 ]
 [3.18]
 [2.2 ]
 [2.62]
 [2.86]


In [256]:
## loss function
e = y_train  - (regr(x1_train,x2_train))
L=(np.sum(e*e, axis=0))*1/2
print (L)

[764.3007]


In [257]:
## deviation

db0=-1*np.sum(e)
db1=-1*np.sum(e*x1_train)
db2=-1*np.sum(e*x2_train)
print (db0)
print (db1)
print (db2)

482.86
1218.1595000000002
1153.3002000000001


In [258]:

b0_list=[]
b1_list=[]
b2_list=[]
L_list=[]

for i in range(0,10000):
    b0_list=b0_list+[b[0]]
    b1_list=b1_list+[b[1]]
    b2_list=b2_list+[b[2]]
    L_list=L_list+[L]
    
    b[0]=b[0]-LR*db0
    b[1]=b[1]-LR*db1
    b[2]=b[2]-LR*db2
    
    e = y_train  - (regr(x1_train,x2_train))
    L=(np.sum(e*e, axis=0))*1/2
    db0=-1*np.sum(e)
    db1=-1*np.sum(e*x1_train)
    db2=-1*np.sum(e*x2_train)
    
    

data=np.array([b0_list]+[b1_list]+[b2_list]+[L_list])
data=data.T
print (data)


[[1.00000000e+00 1.00000000e+00 1.00000000e+00 7.64300700e+02]
 [9.51714000e-01 8.78184050e-01 8.84669980e-01 4.90717166e+02]
 [9.13429873e-01 7.81271346e-01 7.92838474e-01 3.17518826e+02]
 ...
 [1.37080712e+00 8.79865222e-02 5.11954408e-01 1.69006841e+01]
 [1.37080794e+00 8.79859433e-02 5.11954674e-01 1.69006841e+01]
 [1.37080875e+00 8.79853648e-02 5.11954941e-01 1.69006840e+01]]


In [259]:
df = pd.DataFrame(data, columns=list('012L'))
df

0         1         2           L
0     1.000000  1.000000  1.000000  764.300700
1     0.951714  0.878184  0.884670  490.717166
2     0.913430  0.781271  0.792838  317.518826
3     0.883103  0.704173  0.719704  207.870902
4     0.859108  0.642839  0.661446  138.454565
5     0.840150  0.594049  0.615026   94.507470
6     0.825199  0.555238  0.578024   66.684088
7     0.813437  0.524368  0.548517   49.068083
8     0.804211  0.499815  0.524973   37.914031
9     0.797002  0.480289  0.506174   30.850831
10    0.791399  0.464762  0.491151   26.377421
11    0.787072  0.452416  0.479133   23.543531
12    0.783761  0.442601  0.469505   21.747576
13    0.781257  0.434801  0.461781   20.608715
14    0.779396  0.428602  0.455571   19.885851
15    0.778046  0.423678  0.450566   19.426352
16    0.777101  0.419767  0.446520   19.133592
17    0.776479  0.416663  0.443239   18.946402
18    0.776114  0.414200  0.440565   18.826056
19    0.775952  0.412248  0.438375   18.748039
20    0.775952  0.410701  0.436571   18.696831
21    0.776080  0.409477  0.435074   18.662606
22    0.776310  0.408509  0.433822   18.639145
23    0.776621  0.407745  0.432765   18.622509
24    0.776995  0.407143  0.431863   18.610206
25    0.777421  0.406670  0.431086   18.600656
26    0.777886  0.406299  0.430407   18.592862
27    0.778382  0.406009  0.429808   18.586190
28    0.778903  0.405784  0.429272   18.580239
29    0.779443  0.405609  0.428787   18.574756
...        ...       ...       ...         ...
9970  1.370785  0.088002  0.511947   16.900684
9971  1.370786  0.088002  0.511947   16.900684
9972  1.370787  0.088001  0.511948   16.900684
9973  1.370787  0.088001  0.511948   16.900684
9974  1.370788  0.088000  0.511948   16.900684
9975  1.370789  0.087999  0.511948   16.900684
9976  1.370790  0.087999  0.511949   16.900684
9977  1.370791  0.087998  0.511949   16.900684
9978  1.370792  0.087998  0.511949   16.900684
9979  1.370792  0.087997  0.511950   16.900684
9980  1.370793  0.087996  0.511950   16.900684
9981  1.370794  0.087996  0.511950   16.900684
9982  1.370795  0.087995  0.511950   16.900684
9983  1.370796  0.087995  0.511951   16.900684
9984  1.370796  0.087994  0.511951   16.900684
9985  1.370797  0.087993  0.511951   16.900684
9986  1.370798  0.087993  0.511951   16.900684
9987  1.370799  0.087992  0.511952   16.900684
9988  1.370800  0.087992  0.511952   16.900684
9989  1.370801  0.087991  0.511952   16.900684
9990  1.370801  0.087991  0.511953   16.900684
9991  1.370802  0.087990  0.511953   16.900684
9992  1.370803  0.087989  0.511953   16.900684
9993  1.370804  0.087989  0.511953   16.900684
9994  1.370805  0.087988  0.511954   16.900684
9995  1.370805  0.087988  0.511954   16.900684
9996  1.370806  0.087987  0.511954   16.900684
9997  1.370807  0.087987  0.511954   16.900684
9998  1.370808  0.087986  0.511955   16.900684
9999  1.370809  0.087985  0.511955   16.900684

[10000 rows x 4 columns]

In [260]:
df.sort_values(by='L', ascending=True).head(10)

0         1         2          L
9999  1.370809  0.087985  0.511955  16.900684
9998  1.370808  0.087986  0.511955  16.900684
9997  1.370807  0.087987  0.511954  16.900684
9996  1.370806  0.087987  0.511954  16.900684
9995  1.370805  0.087988  0.511954  16.900684
9994  1.370805  0.087988  0.511954  16.900684
9993  1.370804  0.087989  0.511953  16.900684
9992  1.370803  0.087989  0.511953  16.900684
9991  1.370802  0.087990  0.511953  16.900684
9990  1.370801  0.087991  0.511953  16.900684